gitrepos:
  # fleet-local
  - name: fleet-cert-manager
    description: TLS + letsencrypt
    namespace: fleet-local
  - name: fleet-workspace-controller
    description: Split fleet workspaces per users with roles
    namespace: fleet-local
    paths:
      - charts/fleet-workspace-controller
  - name: fleet-gorizond-cluster
    repo: gorizond-cluster
    description: k3s/headscale api saas
    namespace: fleet-local
    paths:
      - charts
  - name: fleet-gorizond-pay-yookassa
    repo: yookassa-url-generator
    description: yookassa integrate with gorizond
    namespace: fleet-local
    paths:
      - charts
  - name: docusaurus
    description: Documentaion + Blog
    namespace: fleet-local
    clientSecretName: auth-rnmxl
    repo_domain: https://gitlab.com
    repo_path: gorizond/gitops
    imageScanCommit:
      authorEmail: i@negash.ru
      authorName: Fleet Bot
      messageTemplate: 'chore(fleet): ImageScan update image'
    imageScanInterval: 15s
  - name: jspolicy-for-autoscaler
    description: Generate autoscaler for all clusters
    namespace: fleet-local
    paths:
      - policy
helmrepos:
  # fleet-local
  - name: jspolicy
    description: JS mutator/validator k8s
    namespace: fleet-local
    helm:
      releaseName: jspolicy
      repo: https://charts.loft.sh
      chart: jspolicy
      values:
        replicaCount: 1
  - name: docker-machine-driver-makecloud
    description: Rancher docker machine driver for makecloud.ru with UI (machine-config + cloud-credential)
    namespace: cattle-ui-plugin-system
    helm:
      releaseName: docker-machine-driver-makecloud
      repo: https://gorizond.github.io/docker-machine-driver-makecloud
      chart: makecloud-node-driver
      version: 0.1.3
  - name: gorizond-ui
    description: Gorizond UI for gorizond clusters
    namespace: cattle-ui-plugin-system
    helm:
      releaseName: gorizond-ui
      repo: https://gorizond.github.io/rancher-ui
      chart: gorizond-ui
      version: 0.1.27
  - name: fleet-workspace-ui
    description: Gorizond UI for split fleet workspaces per users with roles
    namespace: cattle-ui-plugin-system
    helm:
      releaseName: fleet-workspace-ui
      repo: https://gorizond.github.io/fleet-workspace-ui
      chart: fleet-workspace-ui
      version: 0.1.5
      
