gitrepos:
  # fleet-local
  - name: fleet-cert-manager
    description: TLS + letsencrypt
    namespace: fleet-local
  - name: fleet-workspace-controller
    description: Split fleet workspaces per users with roles
    namespace: fleet-local
helmrepos:
  # fleet-local
  - name: jspolicy
    description: JS mutator/validator k8s
    namespace: fleet-local
    helm:
      releaseName: jspolicy
      repo: https://charts.loft.sh
      chart: jspolicy
      values:
        replicaCount: 1
  